/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Clases.*;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Rodrigo
 */
public class MovieUcuFrame extends javax.swing.JFrame {
    
    public Adapter adapter;
    
    /**
     * Creates new form MovieUcuFrame
     */
    public MovieUcuFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jListPeliculas = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaInfoPelicula = new javax.swing.JTextArea();
        jTextFieldBusqueda = new javax.swing.JTextField();
        jComboBoxOpciones = new javax.swing.JComboBox<>();
        jButtonBuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listActores = new javax.swing.JList<>();
        btnEliminarActor = new javax.swing.JButton();
        cmbOpciones = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jListPeliculas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jListPeliculas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListPeliculas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListPeliculasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jListPeliculas);

        jTextAreaInfoPelicula.setColumns(20);
        jTextAreaInfoPelicula.setLineWrap(true);
        jTextAreaInfoPelicula.setRows(5);
        jScrollPane2.setViewportView(jTextAreaInfoPelicula);

        jTextFieldBusqueda.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextFieldBusqueda.setText("Buscar...");
        jTextFieldBusqueda.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextFieldBusqueda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldBusquedaMouseClicked(evt);
            }
        });

        jComboBoxOpciones.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jComboBoxOpciones.setMaximumRowCount(3);
        jComboBoxOpciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nombre", "Año", "Genero" }));
        jComboBoxOpciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxOpcionesActionPerformed(evt);
            }
        });

        jButtonBuscar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonBuscarMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("UCU MOVIE");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Peliculas");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Descripcion");
        jLabel3.setToolTipText("");

        listActores.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        listActores.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(listActores);

        btnEliminarActor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnEliminarActor.setText("Eliminar Actor");
        btnEliminarActor.setToolTipText("");
        btnEliminarActor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarActorMouseClicked(evt);
            }
        });
        btnEliminarActor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActorActionPerformed(evt);
            }
        });

        cmbOpciones.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cmbOpciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Actores", "Productores", "Directores" }));
        cmbOpciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbOpcionesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(211, 211, 211))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBoxOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldBusqueda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(btnEliminarActor)
                                            .addGap(253, 253, 253))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(cmbOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(270, 270, 270))))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(btnEliminarActor)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        adapter = new Adapter();
        adapter.crearAlmacenPeliculas();
        adapter.crearAlmacenActores();
        adapter.crearAlmacenDirectores();
        adapter.crearAlmacenProductores();
        adapter.crearListaPeliculasActores();
        adapter.crearListaPeliculasDirectores();
        adapter.crearListaPeliculasProductores();
        DefaultListModel model = new DefaultListModel();
        DefaultListModel model2 = new DefaultListModel();
        ArrayList<String> peliculas = new ArrayList<>();
        adapter.obtenerNombrePeliculas(adapter.getArbolPeliculas().getRaiz(),peliculas);
        ArrayList<String> actores = new ArrayList<>();
        adapter.obtenerNombreActores(adapter.getArbolActores().getRaiz(), actores);
        for(int i=0;i<peliculas.size();i++){
            model.addElement(peliculas.get(i));
        }
        jListPeliculas.setModel(model);
        for(int i=0; i<actores.size();i++){
            model2.addElement(actores.get(i));
        }
        listActores.setModel(model2);
        
        
    }//GEN-LAST:event_formWindowOpened

    private void jListPeliculasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListPeliculasMouseClicked
        String selected = (String)jListPeliculas.getSelectedValue();
        jTextAreaInfoPelicula.setText(adapter.obtenerInfoPelicula(selected));
    }//GEN-LAST:event_jListPeliculasMouseClicked

    private void jTextFieldBusquedaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldBusquedaMouseClicked
        jTextFieldBusqueda.setText("");
    }//GEN-LAST:event_jTextFieldBusquedaMouseClicked

    private void jButtonBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBuscarMouseClicked
        if(jComboBoxOpciones.getSelectedItem().toString().equals("Nombre")){
            String nombreABuscar = jTextFieldBusqueda.getText();
            ArrayList<String> listaResultados = new ArrayList<String>();
            adapter.buscarPorNombre(nombreABuscar, adapter.getArbolPeliculas().getRaiz(),listaResultados);
            DefaultListModel model = new DefaultListModel();
            for(int i=0;i<listaResultados.size();i++){
                model.addElement(listaResultados.get(i));
            }
            jListPeliculas.setModel(model);   
        }
        else if(jComboBoxOpciones.getSelectedItem().toString().equals("Año")){
            try {
                int yearBuscar= Integer.parseInt(jTextFieldBusqueda.getText());
                ArrayList<String> listaResultados = new ArrayList<>();
                adapter.buscarPorYear(yearBuscar,adapter.getArbolPeliculas().getRaiz(),listaResultados);
                DefaultListModel model = new DefaultListModel();
                for(int i=0;i<listaResultados.size();i++){
                    model.addElement(listaResultados.get(i));
                }
                jListPeliculas.setModel(model);
            }
            catch (NumberFormatException e){
               JOptionPane.showMessageDialog(null, "Esta buscando por año. Ingrese numeros!!!");
            }
            
        }
        else if(jComboBoxOpciones.getSelectedItem().toString().equals("Genero")){
            String generoABuscar = jTextFieldBusqueda.getText();
            ArrayList<String> listaResultados = new ArrayList<>();
            adapter.buscarPorGenero(generoABuscar, adapter.getArbolPeliculas().getRaiz(),listaResultados);
            DefaultListModel model = new DefaultListModel();
            for(int i=0;i<listaResultados.size();i++){
                model.addElement(listaResultados.get(i));
            }
            jListPeliculas.setModel(model); 
            
        }
        
    }//GEN-LAST:event_jButtonBuscarMouseClicked

    private void jComboBoxOpcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxOpcionesActionPerformed
        
        
    }//GEN-LAST:event_jComboBoxOpcionesActionPerformed

    private void cmbOpcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbOpcionesActionPerformed
        if(cmbOpciones.getSelectedItem().toString().equals("Actores")){
            ArrayList<String> actores = new ArrayList<>();
            adapter.obtenerNombreActores(adapter.getArbolActores().getRaiz(), actores);
            DefaultListModel model2 = new DefaultListModel();
            for(int i=0; i<actores.size();i++){
                model2.addElement(actores.get(i));
            }
            listActores.setModel(model2);
            btnEliminarActor.setEnabled(true);
            }
        else if(cmbOpciones.getSelectedItem().toString().equals("Productores")){
            ArrayList<String> productores = new ArrayList<>();
            adapter.obtenerNombreProductores(adapter.getArbolProductores().getRaiz(), productores);
            DefaultListModel model3 = new DefaultListModel();
            for(int i=0; i<productores.size();i++){
                model3.addElement(productores.get(i));
            }
            listActores.setModel(model3);
            btnEliminarActor.setEnabled(false);
        }else if(cmbOpciones.getSelectedItem().toString().equals("Directores")){
            ArrayList<String> directores = new ArrayList<>();
            adapter.obtenerNombreDirectores(adapter.getArbolDirectores().getRaiz(), directores);
            DefaultListModel model4 = new DefaultListModel();
            for(int i=0; i<directores.size();i++){
                model4.addElement(directores.get(i));
            }
            listActores.setModel(model4);
            btnEliminarActor.setEnabled(false);
        }
    }//GEN-LAST:event_cmbOpcionesActionPerformed

    private void btnEliminarActorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActorActionPerformed

    private void btnEliminarActorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarActorMouseClicked
        String selected = (String)listActores.getSelectedValue();
        adapter.eliminarActor(selected);
        ArrayList<String> actores = new ArrayList<>();
        adapter.obtenerNombreActores(adapter.getArbolActores().getRaiz(), actores);
        DefaultListModel model2 = new DefaultListModel();
        for(int i=0; i<actores.size();i++){
            model2.addElement(actores.get(i));
        }
        listActores.setModel(model2);
        ArrayList<String> peliculas = new ArrayList<>();
        adapter.obtenerNombrePeliculas(adapter.getArbolPeliculas().getRaiz(),peliculas);
        DefaultListModel model = new DefaultListModel();
        for(int i=0;i<peliculas.size();i++){
            model.addElement(peliculas.get(i));
        }
        jListPeliculas.setModel(model);
    }//GEN-LAST:event_btnEliminarActorMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MovieUcuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MovieUcuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MovieUcuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MovieUcuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MovieUcuFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarActor;
    private javax.swing.JComboBox<String> cmbOpciones;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JComboBox<String> jComboBoxOpciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jListPeliculas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextAreaInfoPelicula;
    private javax.swing.JTextField jTextFieldBusqueda;
    private javax.swing.JList<String> listActores;
    // End of variables declaration//GEN-END:variables
}
